/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laberintodecretaalpha;

import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author M!ke
 */
public class VentanaGanar extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form VentanaGanar
     */
    
    
    public static VentanaGanar instancia = null;
    
    public static VentanaGanar Singleton()
    {
        if(instancia == null)
        {
            instancia = new VentanaGanar();
            instancia.initComponents();
            instancia.setLocationRelativeTo(null); //Centrar la ventana
            instancia.labelContinuar.setIcon(ImageIconDic.singleton().getImageIcon("menu"));
            instancia.labelContinuar.setVisible(false);
            
            instancia.labelContinuar1.setIcon(ImageIconDic.singleton().getImageIcon("botonSalir"));
            instancia.labelContinuar1.setVisible(false);
            
            instancia.fondo.setIcon(ImageIconDic.singleton().getImageIcon("fondoGanar"));
            
            instancia.repaint();
        }
        return instancia;
    }
    
    
    @Override
    public void paint(Graphics g)
    {
        //jPanel1.getGraphics().drawImage(BufferedImageDic.Singleton().imagen("Gates"), 0, 0, null);
        jPanel1.paintAll(jPanel1.getGraphics());
    }
    
    
    
    
    public VentanaGanar() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelContinuar1 = new javax.swing.JLabel();
        labelContinuar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laberinto de Creta");
        setResizable(false);

        jPanel1.setLayout(null);

        labelContinuar1.setText("continaur");
        labelContinuar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelContinuar1MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelContinuar1MouseExited(evt);
            }
        });
        labelContinuar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelContinuar1MouseMoved(evt);
            }
        });
        jPanel1.add(labelContinuar1);
        labelContinuar1.setBounds(210, 200, 144, 57);

        labelContinuar.setText("continaur");
        labelContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelContinuarMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelContinuarMouseExited(evt);
            }
        });
        labelContinuar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelContinuarMouseMoved(evt);
            }
        });
        jPanel1.add(labelContinuar);
        labelContinuar.setBounds(40, 200, 144, 57);

        fondo.setText("jLabel1");
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelContinuarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuarMousePressed
        VentanaGameOver.gameOverActivado=true;
        try {
            // TODO add your handling code here:

            Control.Singleton().setEstadoJuego(Control.EstadosJuego.Menu);
        } catch (IOException ex) {
            Logger.getLogger(VentanaGameOver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanaGameOver.class.getName()).log(Level.SEVERE, null, ex);
        }

        VentanaGanar.Singleton().setVisible(false);
    }//GEN-LAST:event_labelContinuarMousePressed

    private void labelContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuarMouseExited
        // TODO add your handling code here:
        instancia.labelContinuar.setIcon(ImageIconDic.singleton().getImageIcon("menu"));
    }//GEN-LAST:event_labelContinuarMouseExited

    private void labelContinuarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuarMouseMoved
        // TODO add your handling code here:
        instancia.labelContinuar.setIcon(ImageIconDic.singleton().getImageIcon("menuHover"));
    }//GEN-LAST:event_labelContinuarMouseMoved

    private void labelContinuar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuar1MousePressed
        System.exit(0);
        VentanaGameOver.Singleton().setVisible(false);
    }//GEN-LAST:event_labelContinuar1MousePressed

    private void labelContinuar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuar1MouseExited
        // TODO add your handling code here:
        instancia.labelContinuar1.setIcon(ImageIconDic.singleton().getImageIcon("botonSalir"));
    }//GEN-LAST:event_labelContinuar1MouseExited

    private void labelContinuar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuar1MouseMoved
        // TODO add your handling code here:
        instancia.labelContinuar1.setIcon(ImageIconDic.singleton().getImageIcon("botonSalirHover"));
    }//GEN-LAST:event_labelContinuar1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGanar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel labelContinuar;
    public static javax.swing.JLabel labelContinuar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            //System.out.println("escape");
            System.exit(0);
        }
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
    
    
    void adKey() throws FileNotFoundException, IOException {
        //throw new UnsupportedOperationException("Not yet implemented");
        addKeyListener(Singleton());
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono/icono2.gif")));
    }
}
