/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laberintodecretaalpha;

import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author M!ke
 */
public class VentanaProgreso extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form VentanaGameOver
     */
    public static VentanaProgreso instancia = null;
    public static Timer timer;
    
    public static VentanaProgreso Singleton() throws InterruptedException
    {
        if(instancia == null)
        {
            instancia = new VentanaProgreso();
            instancia.initComponents();
            instancia.setLocationRelativeTo(null); //Centrar la ventana
            //instancia.labelJugar.setIcon(ImageIconDic.singleton().getImageIcon("jugar"));
            instancia.fondo.setIcon(ImageIconDic.singleton().getImageIcon("Cargar"));
            instancia.fondoProgressBar.setIcon(ImageIconDic.singleton().getImageIcon("botonGrande"));
            instancia.lableCargando.setIcon(ImageIconDic.singleton().getImageIcon("botonCargando"));
            instancia.progressBar.setValue(0);
            instancia.repaint();
        }
        return instancia;
    }
    
    
    @Override
    public void paint(Graphics g)
    {
        //jPanel1.getGraphics().drawImage(BufferedImageDic.Singleton().imagen("Gates"), 0, 0, null);
        jPanel1.paintAll(jPanel1.getGraphics());
    }
    
    
    public VentanaProgreso() throws InterruptedException {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        fondoProgressBar = new javax.swing.JLabel();
        lableCargando = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laberinto de Creta");
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(progressBar);
        progressBar.setBounds(90, 210, 217, 20);

        fondoProgressBar.setMaximumSize(new java.awt.Dimension(236, 57));
        fondoProgressBar.setMinimumSize(new java.awt.Dimension(236, 57));
        fondoProgressBar.setPreferredSize(new java.awt.Dimension(236, 57));
        jPanel1.add(fondoProgressBar);
        fondoProgressBar.setBounds(80, 190, 236, 57);
        jPanel1.add(lableCargando);
        lableCargando.setBounds(80, 110, 236, 57);

        fondo.setText("fondo");
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 400, 300);
        fondo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaProgreso().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(VentanaProgreso.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoProgressBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lableCargando;
    public static javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            //System.out.println("escape");
            System.exit(0);
        }
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
    
    
    void adKey() throws FileNotFoundException, IOException, InterruptedException {
        //throw new UnsupportedOperationException("Not yet implemented");
        addKeyListener(Singleton());
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono/icono2.gif")));
    }
}
