/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laberintodecretaalpha;

import java.awt.Graphics;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author M!ke
 */
public class VentanaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuPrincipal
     */
    
    public static VentanaConfiguracion instancia = null;
    public static boolean prenderMusica = true;
    
    public static VentanaConfiguracion Singleton()
    {
        if(instancia == null)
        {
            instancia = new VentanaConfiguracion();
            instancia.initComponents();
            instancia.setLocationRelativeTo(null);// Centrar la ventana
            instancia.labelGuardar.setIcon(ImageIconDic.singleton().getImageIcon("botonGuardar"));
            instancia.labelCancelar.setIcon(ImageIconDic.singleton().getImageIcon("botonCancelar"));
            instancia.fondo.setIcon(ImageIconDic.singleton().getImageIcon("fondoMenuPrincipal"));
            instancia.fondo.setIcon(ImageIconDic.singleton().getImageIcon("fondoMenuPrincipal"));
            instancia.labelMusica.setIcon(ImageIconDic.singleton().getImageIcon("botonMusica"));
            instancia.chkMusica.setSelected(true);
            
            instancia.repaint();
        }
        return instancia;
    }
    
    
    @Override
    public void paint(Graphics g)
    {
        //jPanel1.getGraphics().drawImage(BufferedImageDic.Singleton().imagen("Gates"), 0, 0, null);
        jPanel1.paintAll(jPanel1.getGraphics());
    }
    
    
    public VentanaConfiguracion() {
        //initComponents();
        setIcon(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelGuardar = new javax.swing.JLabel();
        labelCancelar = new javax.swing.JLabel();
        chkMusica = new javax.swing.JCheckBox();
        labelMusica = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laberinto de Creta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        labelGuardar.setText("jugar");
        labelGuardar.setPreferredSize(new java.awt.Dimension(144, 57));
        labelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelGuardarMousePressed(evt);
            }
        });
        labelGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGuardarMouseMoved(evt);
            }
        });
        jPanel1.add(labelGuardar);
        labelGuardar.setBounds(50, 200, 144, 57);
        labelGuardar.getAccessibleContext().setAccessibleDescription("jugar");

        labelCancelar.setText("jugar");
        labelCancelar.setPreferredSize(new java.awt.Dimension(144, 57));
        labelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelCancelarMousePressed(evt);
            }
        });
        labelCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelCancelarMouseMoved(evt);
            }
        });
        jPanel1.add(labelCancelar);
        labelCancelar.setBounds(200, 200, 144, 57);

        chkMusica.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(chkMusica);
        chkMusica.setBounds(200, 70, 21, 21);

        labelMusica.setText("jLabel1");
        jPanel1.add(labelMusica);
        labelMusica.setBounds(50, 50, 144, 57);

        fondo.setText("jLabel1");
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 400, 300);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseMoved
        // TODO add your handling code here:
         instancia.labelGuardar.setIcon(ImageIconDic.singleton().getImageIcon("botonGuardarHover"));
    }//GEN-LAST:event_labelGuardarMouseMoved

    private void labelGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMousePressed
        // TODO add your handling code here:
        if(chkMusica.isSelected())
        {
            prenderMusica = true;
        }else
        {
            prenderMusica = false;
        }
        String botonJugarAudio = "load.wav";
        InputStream in = null;
        try {
            in = new FileInputStream(botonJugarAudio);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        AudioStream nivel1 = null;
        try {
            nivel1 = new AudioStream(in);
        } catch (IOException ex) {
            Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(prenderMusica)
        {
            AudioPlayer.player.start(nivel1);
        }
        
        try {
            try {
                
                    //System.out.println("oli2");
                    Control.Singleton().setEstadoJuego(Control.EstadosJuego.Menu);
                
                //AudioPlayer.player.stop(nivel1);
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        VentanaConfiguracion.Singleton().setVisible(false);
    }//GEN-LAST:event_labelGuardarMousePressed

    private void labelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseExited
        // TODO add your handling code here:
        instancia.labelGuardar.setIcon(ImageIconDic.singleton().getImageIcon("botonGuardar"));
    }//GEN-LAST:event_labelGuardarMouseExited

    private void labelCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelarMouseExited
        // TODO add your handling code here:
        instancia.labelCancelar.setIcon(ImageIconDic.singleton().getImageIcon("botonCancelar"));
    }//GEN-LAST:event_labelCancelarMouseExited

    private void labelCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelarMousePressed
        // TODO add your handling code here:                                                                                                                                                                                                                                                                                                                                                                                                                                  
        if(prenderMusica == false)
        {
            chkMusica.setSelected(false);
        }
        String botonJugarAudio = "load.wav";
        InputStream in = null;
        try {
            in = new FileInputStream(botonJugarAudio);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        AudioStream nivel1 = null;
        
        try {
            nivel1 = new AudioStream(in);
        } catch (IOException ex) {
            Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(prenderMusica)
        {
            AudioPlayer.player.start(nivel1);
        }
        
        
        VentanaConfiguracion.Singleton().setVisible(false);
        try {
            try {
                Control.Singleton().setEstadoJuego(Control.EstadosJuego.Menu);
                //AudioPlayer.player.stop(nivel1);
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelCancelarMousePressed

    private void labelCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelarMouseMoved
        // TODO add your handling code here:
        instancia.labelCancelar.setIcon(ImageIconDic.singleton().getImageIcon("botonCancelarHover"));
    }//GEN-LAST:event_labelCancelarMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaConfiguracion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkMusica;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCancelar;
    private javax.swing.JLabel labelGuardar;
    private javax.swing.JLabel labelMusica;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono/icono2.gif")));
    }
}
